### ISSUE TITLE
How Does Garbage Collection Work?

### ISSUE THREAD

**Issue by MohammadSianaki** [irlogcat/android-interview-questions#1]
- Tracing Garbage Collection vs Reference Counting
- What is Mark-and-Sweep Algorithm?
- Difference between Young Generation, OldGen and PermanentGen
- PermGen vs MetaSpace?
- What is G1 Garbage Collector?

**Comment by abbas-oveissi** [comment]
من همه سوال‌های توی این ایشو رو تبدیل به ایشوهای جداگونه کردم. برای همین دیگه این ایشو رو میبندم
