### ISSUE TITLE
Data Structures

### ISSUE THREAD

**Issue by MohammadSianaki** [irlogcat/android-interview-questions#3]
- How does ArrayList work internally?
- How does Hashmap work internally?
- What is the optimization to hashmap implementation since Java8 ?
- Hashmap vs LinkedHashMap vs TreeMap?
- Why to choose ConcurentHashMap over SynchronizedMap?

**Comment by abbas-oveissi** [comment]
من همه سوال‌های توی این ایشو رو تبدیل به ایشوهای جداگونه کردم. برای همین دیگه این ایشو رو میبندم
