### ISSUE TITLE
Multi-Threading

### ISSUE THREAD

**Issue by MohammadSianaki** [irlogcat/android-interview-questions#4]
- Process vs Thread
- Kernel Threads vs User Threads
- What is Daemon thread?
- States in lifecycle of a thread?
- Monitor vs Mutex vs Semaphore?
- What is ThreadPool and how it works internally?
- What is ContextSwitch?
- Cooperative multitasking vs Preemptive multitasking ?

**Comment by abbas-oveissi** [comment]
من همه سوال‌های توی این ایشو رو تبدیل به ایشوهای جداگونه کردم. برای همین دیگه این ایشو رو میبندم
